name: Build iOS IPA (unsigned)

on:
  push:

jobs:
  build-ios:
    name: Build iOS (unsigned)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.32.5'

      - name: Install dependencies
        run: flutter pub get

      - name: Select Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer

      - name: Print Xcode version
        run: xcodebuild -version

      - name: Download iOS Platform
        run: xcodebuild -downloadPlatform iOS

      - name: Build unsigned IPA
        run: flutter build ipa --release --no-codesign

      - name: List IPA files
        run: ls -R build/ios/ipa || true

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: build/ios/ipa/Runner.ipa
          if-no-files-found: error
