name: Build iOS IPA (unsigned)

on:
  push:

jobs:
  build-ios:
    name: Build iOS (unsigned)
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.32.5

      - name: Install dependencies
        run: flutter pub get

      - name: Select Xcode 16.2
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app/Contents/Developer

      - name: Print Xcode version
        run: xcodebuild -version

      - name: Build unsigned app (.app)
        run: flutter build ios --release --no-codesign

      - name: Create unsigned IPA
        run: |
          mkdir -p Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
          rm -rf Payload

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-unsigned-ipa
          path: Runner.ipa
